sudo: required
notifications:
  email: false
services:
- docker
language: python
python:
- 3.6
git:
  depth: false
script:
- make build
- make push
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis-deploy.sh
  on:
    branch: master
env:
  global:
  - secure: P5wjzutnWIA88ADB3Uu8H/pOmErK5FDZGne9+REWX8vNhlCLFkeWldzelunlFMAFBxDPXWQ993PA59cjTDvh97JSf/9i9mAUwDPeRKIUXX8fNUmvh/oQoEzuGhBoKLBcNaIUlIkI52yV3OjOFY3jnHWfskMSROgDfi8poC9Svx1t+C8mzFHQI0hbsy6aDXwW3WSFtxdG5Fm898tNzprjq4vhZDVU9ESlllcWpatQ4muR6cuIx4axoH+dBuSqCfHjSZg1tcAes2W7S4Xn64I0PqXORCqqdgYq/SD1tY0dz/T94YmldkSEtBNJMZc62rYR0jjApp+qF2rkXY/vu2VE5TaJQcFQO3MYDfqw8fZYvy9y1KM0KQzypj2in5Lx3KBBgVymZYYQ21n/KyrfUDMneZG2iRedmxeNyeJRIg8gxKbQwLAGJaC6JBdRB7GHi936cWCplS/B60sL12RVVuquXaj6Aojd9B1N8sg+PtUGQ0kN1lBMFAdiMhm709yJEIr4oR/jqxG1DDeqX/kVLViiMnEOe1vB8em6c8N1tvRaV+KRZ3PT0q6/VPmpDhclJBE2IVtQ27Zp7TdY0gYRJd3lVT5L73SGsRkURcON7AJlpNlqp4DSe+xCqfrr4RHnDIMK6MVL182t4zbzEpDu6OdglrrlSfe7+AmO1vltGpUcrwc=
  - secure: ExrZaZ/N/f0diJUypHZ8X8wCfy5dBYrziDo+euAEnYoqupwFwTI5mnxin6vxussKpwPt2/WLbrcIjNog7OCEsoo9UwuxFZHuaT4JRx+50esXpPA7QF5+H/W2g7FCiUbDhMetj/z7sfxKI9mDYDi3yjj+hEOzjReBv0eE1IcevLJ9fvjWlXdqCsLO0iNtB0OJ4CKKcAEShxJzEpLWXvz2+IDjTRjdgrAGESs1kVQLUE1/ERBgFR0Slsz0zNp6o/2hEEzAuFn70h+VsxbVuxKDAdOKAeEqUnsBHJ4Ye3fl+NVvcEP4C/5iFoTuKl2T6SAee9t2YLuwAJo+KKySbQxttOfL0L8p/tdpKUXKGJvXASevelgtiGlXtKxBPJfyLVKtetyb0It/DXQaf5+jstUbKSLNPtLM+x2Yfd/hY65EPcUCQvnClhV3LUKhAjy7gD6e0cLJm4GU0XvJE5gpmGFLBGw+2UTBURLeaV+K6kwDAI8G6F9twAfby22alSTNztHhBQ92QS+XshQs8slo6XjkX20pHClpcDfC/kr2lywBV3l+4zAQ0bKo3vt4HRWTmKH2yafQJHPTq7GUI8ct/V5bwu8VTvCQrgVGT9une3ichnYyfEwUh/zxbGFXFip/I0G1wcJ+9/ctvAZAxel00TexEVglS8neN2NNpvQJxn/Fsss=
