sudo: required
notifications:
  email: false
services:
- docker
language: python
python:
- 3.6
git:
  depth: false
script:
- make build
- make push
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis-deploy.sh
  on:
    branch: master
env:
  global:
  - secure: hTsImtyqiCVccAZS0H7CSWRYmzd70zp0wBXXfWu2zk826hDJnPIfwXDj+tUHj+L8C09ERrzSuHT2SHn0i9IUQPMPejBAFItZJswDgOm8XdNXMGCsr7IXiEcpbzmDMwRhUst0Vkb7uDh9oAdWmTrzAtLQX8/XyeDCWtyJebCKAOh+/k0ds1528KJ3E2+D/rOwtG/AHfsWp+vYVaIUixWi8WCjv5raYPteO4aht7piIcATVMFt7071A4S5/Fux/wzWh6udw5+7dUqjVYKdJMdc+LBdyhu5kYDpymIeQqLuhFxhFj0z/m7+L9Sx6K4Y/v0DJ9fseSxJRZyc863Xs0w5341cRzUZyTK5hgHAsmzko4f/92f95bT0njKovC7TwbJmMhLTMK8yXBXlt9XnTXKBNJbpS6X7l+5sF5lV5e56MmE3etsjtHrKHIZpST1jjCbEJnATFYxfkoxvPGMqr00URF6VITmsPfzoWozm8KB+0vD6bNS1nro6l2qrHBPPK3Uzx6qrRKaWn4KF9HZyp+yvPoMPL8n02qSqRX6P2euGNDAXvifvrBZpleaJPDkusy6DzaA0AWHQLfkwMQxYZ7hq9D2p/vUPUxmAp+9v9Do1Sx3nm81vRL9CRQJP+16UOzoDLUwMpCXUmMDr3w0akqUbHkBH8fd9qh4AFgMzAmRf89I=
  - secure: n3NrNcMTTrxw3qEUA8iFBqsn6+ej6ZKVOhyzImvODJGAGUxVpIuzmN3NExMUC8rPs05ojF/rIfRsna+yQ6QoDPLfJgVLmy40YGcufEJOSonwNSfh7Uxl3F81fYqPC6cLzpGZhBNAmEFgq0igPkymCsDjULO7UA0Ff+3n6pbTaTI5TBoyGjH4lqoKe7onONLkPuvEnDO6HTKdVpnX9CMtVtohPYA0Zb364/ro092tbQnOGKDl6b0Kqca3BWEPe7MxdKUvtquiMAnt0nIqJ1lbSFxmC27fST3AqzMvtbczmL9AFO1jLFmFmbFkzfx42RACWfyGfGpCWAjvqKlCdt/zadxdfvP46T8EXBYkHv5s7bReJDVnLb3B4sWBPF2LR3QQcXFuFno9NzkkVh6eva5Vf6jqKRyu88d9yLh5sXUjhbY4RfoQRdQmTInf2eCXo+iWsACyHon+Elh47uY19zTaGyPcZOByenCJwJJfClBqggDCcGExmUAv4zZfkWiOzMCjzbyMhag2QsOova7h1695CmHxEJyt6Yz6pWoHmxDCxdU02cy4X46Tusudv1mhSeXDQpOV+JbhmEUHVyCdjozJvGjKrU0CawNLEm7xWSuQjEGLs5v2pHfuUz8ZwgmGOSr0kCeW+4FipgV0oJt076YWb6wLMOtgLYppYrhpRb7G1e8=
